### ISSUE TITLE
rest api

### ISSUE THREAD

**Issue by Alexander-Mochinov** [DonikHronic/Aments-Shop#1]
в папке aments_shop создай папку api в ней файлы
viewsets.py
serializers.py
urls.py

в viewsets перенеси все вьюшки которые помечены декаратором api_view
в serializers перенеси все сериализаторы 
в urls перенеси все урлы которые отвечают за api urls

в главном urls в aments_shop импортни урлы из папки api/urls.py  и подключи их

**Comment by DonikHronic** [comment]
Выполнено
